Nataly hw1 task1
javaGuruBY/java-free-stream-3 pull request #1
Opened 2020-03-08 12:02 UTC by ezeva

2020-03-14 10:59 UTC, Alexhorosko submitted a review, later dismissed

2020-03-16 20:45 UTC, MisterTopDeveloper requested changes
Наташа, добавь, пожалуйста еще примеров. По заданию не менее 10 примеров.

2020-03-17 18:46 UTC, alexeybobrow approved these changes
LGFM

2020-03-18 07:43 UTC, MisterTopDeveloper commented
> Наташа, добавь, пожалуйста еще примеров. По заданию не менее 10 примеров.

Уточнил у Максима. Если принцип понятен, необязательно приводить мин. кол-во примеров.

2020-03-18 07:45 UTC, MisterTopDeveloper approved these changes
lgfm

2020-03-18 12:09 UTC, puhachou approved these changes

2020-03-18 12:10 UTC, merged